### ISSUE TITLE
[BUG] Script doesn't working properly.

### ISSUE THREAD

**Issue by sirldev** [hansolbangul/generate-router#1]
안녕하세요!
우선 블로그 너무나 잘 보고 있고 만들어주신 라이브러리가 잘 작동되었으면 해서 이슈 남깁니다.

## Bug Description
`create-next-app` 을 통해 샘플 앱을 하나 생성했고, 이 라이브러리를 설치했습니다.
그리고 README.md의 내용을 따라서 script 를 아래와 같이 추가했습니다.

<img width="597" alt="스크린샷 2024-12-04 오후 7 14 37" src="https://github.com/user-attachments/assets/783fed5e-87e4-49e5-9938-a9c1f9c35a3d">

실행 시, 아래와 같은 결과가 나옵니다.

<img width="600" alt="스크린샷 2024-12-04 오후 7 14 51" src="https://github.com/user-attachments/assets/c95dec91-7826-475a-9cf6-d0bda09d4cd6">

코드를 확인해보니, `determineRouteType` 함수에서 path를 가져올 때 문제가 있어보입니다.

또한, path 문제 처리 후에 생성된 타입 파일을 보니, DynamicPaths 가 빈값으로 넘어오는 걸로 보입니다.
아마 DynamicPaths 인 라우트가 없을 경우가 구현이 되어있지 않은 것 같은데,
제가 내일중으로 한번 작업해봐도 괜찮을까요?

혹시 작업중이시면 기다리고 있겠습니다 :)

**Comment by hansolbangul** [comment]
안녕하세요 @sirldev님!

확인해보니, determineRouteType 쪽에서 경로를 읽는 방식과, DynamicPaths가 동적 경로가 없을때의 상황 두개 모두 말씀주신대로 버그가 확인되었습니다.

JunHyeok님이 수정해주신다면 좋을 것 같습니다! 수정 후 PR 부탁드릴게요 :D

**Comment by hansolbangul** [comment]
해당 내용은, 버그로 문의가 너무 계속 들어와서 먼저 수정을 진행했습니다.

[Commit 83df8d8](https://github.com/hansolbangul/generate-router/commit/83df8d8b6f4072306ff00dbaa7f3543b0f9ba24f)

다른 개선 사항이 있다면 언제든지 PR부탁드립니다.

해당 issue는 닫도록 하겠습니다.

**Comment by sirldev** [comment]
네~! 감사합니다
